server:
  port: 8023
spring:
  application:
    name: auth-server
  datasource:
    url: jdbc:postgresql://localhost:5432/credentials
    username: postgres
    password: h4ckm3
  jpa:
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
    hibernate:
      ddl-auto: update
      show-sql: true